dependencies {
    implementation "com.github.ben-manes.caffeine:caffeine:${caffeineVersion}"
    implementation "com.googlecode.xmemcached:xmemcached:${xMemcachedVersion}"
    implementation "org.springframework:spring-beans:${springVersion}"
    implementation 'com.google.guava:guava:33.5.0-jre'
    implementation 'io.micrometer:micrometer-core:1.16.4'
    implementation 'org.eclipse.collections:eclipse-collections-api:13.0.0'
    implementation 'org.eclipse.collections:eclipse-collections:13.0.0'
    implementation 'com.google.protobuf:protobuf-java:4.34.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.21.2'
}
