global:
  scrape_interval:     3s
  evaluation_interval: 3s

# ~ scrape configuration containing exactly one endpoint to scrape
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app-scrape-job'
    scrape_interval: 3s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
