plugins {
    id 'java'
    id 'application'
    id 'idea'
}

dependencies {
    implementation project(':sandbox:distributed-algorithms:cluster-core')
    implementation project(':sandbox:distributed-search:search-server-api')
}

application {
    mainClass = 'search.SearchServerRunner'
}

jar {
    archiveBaseName = 'search-server'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': application.mainClass
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    dependsOn(':sandbox:distributed-algorithms:cluster-core:jar')
    dependsOn(':sandbox:distributed-search:search-server-api:jar')
}
